from enum import Enum

class State(Enum):
    ZERO_PERCENTS = 0
    THREE_PERCENTS = 0.03
    THREE_POINT_FIVE_PERCENTS = 0.035
    FOUR_PERCENTS = 0.04
    FOUR_POINT_FIVE_PERCENTS = 0.045
    FIVE_PERCENTS = 0.05
    FIVE_POINT_FIVE_PERCENTS = 0.055
    SIX_PERCENTS = 0.06
    SIX_POINT_FIVE_PERCENTS = 0.065
    SEVEN_PERCENTS = 0.07
    SEVEN_POINT_FIVE_PERCENTS = 0.075
    EIGHT_PERCENTS = 0.08
    EIGHT_POINT_FIVE_PERCENTS = 0.085
    NINE_PERCENTS = 0.09
    NINE_POINT_FIVE_PERCENTS = 0.095
    TEN_PERCENTS = 0.1

class Sign(Enum):
    POSITIVE = 1
    NEGATIVE = -1